name: CI/CD Pipeline with SonarQube & Docker Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Run Linting (flake8)
        run: flake8 . --count --show-source --statistics --exit-zero

      - name: Install Sonar Scanner
        run: |
          curl -o sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner.zip
          export PATH=$PATH:$(pwd)/sonar-scanner-5.0.1.3006-linux/bin
          sonar-scanner --version

      - name: Run SonarScanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=akash-trivy-sonar \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://13.232.4.242:9091  \
            -Dsonar.login=sqp_d1b0751b50dfe59f5d63f0644e29a28b6e3

      - name: SonarQube Quality Gate Check
        id: sonar_quality_gate
        run: |
          sudo apt-get install -y jq
          STATUS=$(curl -s -u sqp_ccae52bfe1a866d4c67c58ab05c6e2ad1bec468d: \
          "http://13.232.4.242:9091/api/qualitygates/project_status?projectKey=akash-trivy-sonar" \
          | jq -r '.projectStatus.status')

          echo "Quality Gate Status: $STATUS"
          if [[ "$STATUS" != "OK" ]]; then
            echo "❌ SonarQube Quality Gate failed!"
            exit 1
          fi

  docker:
    needs: sonar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Image Tag
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          IMAGE_NAME="akashigt/akash-trivy-sonar:${COMMIT_HASH}_${TIMESTAMP}"
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          echo "Building Docker image with tag $IMAGE_NAME"
          docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Scan Docker Image for Vulnerabilities
        id: trivy_scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.IMAGE_NAME }}"
          format: "table"
          exit-code: 1 # Fails pipeline if vulnerabilities are found
          ignore-unfixed: true

      - name: Log in to Docker Hub
        if: success()
        run: echo "${{ secrets.PASS }}" | docker login -u "${{ secrets.USER }}" --password-stdin

      - name: Push Docker Image
        if: success()
        run: |
          docker push ${{ env.IMAGE_NAME }}
          echo "✅ Docker image pushed: ${{ env.IMAGE_NAME }}"
